import argparse
import json
import logging
import subprocess
from functools import partial
from pathlib import Path
from typing import Callable, Optional

import yaml


def evaluate(
    evaluator: Callable[[], subprocess.CompletedProcess],
) -> dict[str, dict[str, str]]:
    eval_process = evaluator()
    try:
        eval_process.check_returncode()
    except subprocess.CalledProcessError:
        logging.error(
            dict(
                eval_process_stdout=eval_process.stdout,
                eval_process_stderr=eval_process.stderr,
            )
        )
        raise

    workflows_json = eval_process.stdout
    workflows: dict[str, dict[str, str]] = json.loads(workflows_json)
    return workflows

def yaml_multiline_string_pipe(dumper, data):
    text_list = [line.rstrip() for line in data.splitlines()]
    fixed_data = "\n".join(text_list)
    if len(text_list) > 1:
        return dumper.represent_scalar('tag:yaml.org,2002:str', fixed_data, style="|")
    return dumper.represent_scalar('tag:yaml.org,2002:str', fixed_data)

yaml.add_representer(str, yaml_multiline_string_pipe)

def get_git_toplevel() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        text=True,
        capture_output=True,
        check=True,
    )
    return Path(result.stdout.strip())

def main(evaluated_ci_path: Optional[Path], prepend_git_root: bool = True):
    git_toplevel = get_git_toplevel() if prepend_git_root else None

    if evaluated_ci_path is None:
        eval_process = partial(
            subprocess.run,
            [
                "nix",
                "eval",
                "--option",
                "experimental-features",
                "nix-command flakes",
                ".#ci.workflows",
                "--json",
            ],
            text=True,
            capture_output=True,
        )
        workflows = evaluate(evaluator=eval_process)
    else:
        workflows = json.loads(evaluated_ci_path.read_text())

    for key, value in workflows.items():
        if prepend_git_root:
            render_path = git_toplevel / key
        else:
            render_path = Path(key)
        render_path.parent.mkdir(exist_ok=True, parents=True)
        print(f"Writing to {render_path}")
        header = f"""# This file was autogenerated by actions.nix. Do not edit it manually.
# To make changes, edit the workflow definition in your flake's actions-nix configuration
# (typically under flake.actions-nix.workflows."{key}") and run:
#   nix run .#render-workflows
# Or commit to trigger the pre-commit hook if enabled.
"""
        render_path.write_text(header + yaml.dump(value))


if __name__ == "__main__":
    argparser = argparse.ArgumentParser()
    argparser.add_argument("--evaluated-ci-path", required=False)
    argparser.add_argument(
        "--no-prepend-git-root",
        action="store_true",
        help="Do not prepend the git repo root to workflow paths"
    )
    args = argparser.parse_args()
    main(
        evaluated_ci_path=Path(args.evaluated_ci_path) if args.evaluated_ci_path else None,
        prepend_git_root=not args.no_prepend_git_root,
    )

